name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # select python version?

    - name: install-requirements
      run: pip install -r requirements.txt
    
    - name: test
      run: python3 test.py
